services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: node server.js
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - plots:/app/plots
    environment:
      NODE_ENV: production
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-cookies}

volumes:
  plots:
